// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBtn: typeof import('./src/components/BaseBtn/BaseBtn.vue')['default']
    BaseComponent: typeof import('./src/components/BaseComponent.vue')['default']
    BaseCounter: typeof import('./src/components/BaseCounter/BaseCounter.vue')['default']
    BaseExpansiveCard: typeof import('./src/components/BaseCard/BaseExpansiveCard.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader/BaseHeader.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal/BaseModal.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable/BaseTable.vue')['default']
    Btn: typeof import('./src/components/buttons/Btn.vue')['default']
    ClientTable: typeof import('./src/components/ClientTable/ClientTable.vue')['default']
    ExpandTransition: typeof import('./src/components/ExpandTransition.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader/MainHeader.vue')['default']
    OrderModal: typeof import('./src/components/OrderModal/OrderModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
